name: pydata-ssm
channels:
- conda-forge
dependencies:
  - ipykernel
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - numba
  - numpy
  - numpyro
  - nutpie
  - pandas
  - preliz
  - pymc-base
  - scikit-learn
  - scipy
  - statsmodels
  - watermark
  - pip
  - pip:
    - jax
    - blackjax
